import {
  matchOption,
  matchOptionValue,
  isUsableLabel,
  looksLikeHumanLabel,
  type FieldDescriptor,
  type FieldMeta,
} from "@offeros/autofill";
import { groupByMeta } from "./field-meta-bridge";
import type { AtsRecipe } from "./recipes";
import { deepQueryAll } from "./deep-query";
import {
  fillAriaChoice,
  fillAriaPopup,
  isAriaChoice,
  isAriaPopupControl,
  ariaControlValue,
  ariaGroupMembers,
  ariaOptionLabel,
} from "./aria-driver";
import {
  COMBOBOX_FILL,
  isComboboxResultMsg,
  SKILLS_FILL,
  isSkillsResultMsg,
} from "./combobox-protocol";

/**
 * Deterministic, content-derived field ids. The old session counter reset on
 * every content-script reload and reassigned the same `offeros-N` names to
 * DIFFERENT fields in the new DOM order — any state keyed by fieldId across a
 * reload (rehydrated reports, written rows) then painted onto the wrong rows.
 * Hashing the field's stable signals (type|name|label|autocomplete) gives the
 * same logical field the same id on every scan of the same form; `used`
 * disambiguates true duplicates by DOM order.
 */
function stableFieldId(sig: string, used: Map<string, number>): string {
  let h = 0;
  for (let i = 0; i < sig.length; i += 1) h = (h * 31 + sig.charCodeAt(i)) | 0;
  const base = (h >>> 0).toString(36);
  const n = used.get(base) ?? 0;
  used.set(base, n + 1);
  return n === 0 ? `offeros-${base}` : `offeros-${base}-${n}`;
}

/** A "required" marker carried on the TITLE element's class list — ATSes that
 *  render the asterisk as a CSS pseudo-element (Ashby: `_required_…`) leave
 *  nothing in textContent, so the class is the only DOM-visible signal. */
function classSaysRequired(el: Element | null): boolean {
  return el !== null && /(^|[^a-z])required/i.test(String(el.className ?? ""));
}

/** Text of a node with its own controls removed — a wrapping label minus the
 *  input it wraps, a row container minus the widget it holds. */
function textWithoutControls(node: Element): string {
  const clone = node.cloneNode(true) as HTMLElement;
  for (const control of Array.from(
    clone.querySelectorAll("select, input, textarea, button, [role=listbox], [role=option]"),
  )) {
    control.remove();
  }
  return clone.textContent?.replace(/\s+/g, " ").trim() ?? "";
}

/** Is this element the one a person can actually see? Same-id twins are common
 *  (a live field and a hidden template copy); the visible one is the real one. */
function isVisible(el: Element): boolean {
  const style = el.ownerDocument.defaultView?.getComputedStyle(el);
  if (style && (style.display === "none" || style.visibility === "hidden")) return false;
  const rect = (el as HTMLElement).getBoundingClientRect?.();
  // happy-dom and jsdom report 0×0 for everything, so an absent/zero rect is
  // only disqualifying when SOMETHING on the page has a non-zero one.
  if (!rect) return true;
  return rect.width > 0 || rect.height > 0 || !documentHasLayout(el.ownerDocument);
}

/** True when this document reports real geometry at all. In a test DOM nothing
 *  does, and treating every element as invisible there would break every scan. */
function documentHasLayout(doc: Document): boolean {
  const body = doc.body;
  const rect = body?.getBoundingClientRect?.();
  return rect !== undefined && (rect.width > 0 || rect.height > 0);
}

/**
 * A label element bound to this field by an id CONVENTION rather than by `for`.
 *
 * Forms generated by a framework often name their label after their input —
 * `crc-label-<inputId>`, `label_<inputId>`, `<inputId>-label`. No `for`
 * attribute, no wrapping, nothing the HTML spec would call an association, but
 * a deterministic one all the same. Recognising the shape rather than any one
 * platform's prefix is what makes this general: it is the same trick everywhere,
 * only the prefix changes.
 */
function labelByIdConvention(el: HTMLElement, key: string): Element | null {
  const doc = el.ownerDocument;
  for (const candidate of Array.from(doc.querySelectorAll("label[id]"))) {
    const labelId = candidate.getAttribute("id") ?? "";
    if (labelId === key) continue;
    const related =
      (labelId.endsWith(key) && /label/i.test(labelId.slice(0, labelId.length - key.length))) ||
      (labelId.startsWith(key) && /label/i.test(labelId.slice(key.length)));
    if (related && isVisible(candidate)) return candidate;
  }
  return null;
}

/**
 * A label carried as a component's own property.
 *
 * Component frameworks put the human name of a control in an attribute on the
 * wrapper that renders it — `cx-prop-label`, `data-label`, `lt-prop-label`. The
 * pattern is "an attribute whose NAME contains label", which is what this
 * matches; no framework's spelling is hard-coded, because the spelling is the
 * only part that differs between them.
 *
 * Held to a stricter bar than visible text (`looksLikeHumanLabel`): an
 * attribute value has not been through a designer, so it is as likely to hold a
 * template expression or an id as a question.
 */
function labelFromAncestorProp(el: HTMLElement, budget: number): string {
  let node: Element | null = el;
  for (let depth = 0; depth <= budget && node; depth += 1, node = node.parentElement) {
    // Same guard the row rung uses: a container holding several controls
    // describes all of them, so its label belongs to none in particular.
    if (depth > 0 && node.querySelectorAll("input, select, textarea").length > 2) break;
    for (const attr of Array.from(node.attributes)) {
      if (!/label/i.test(attr.name)) continue;
      // ARIA attributes are excluded outright. `aria-label` has a defined
      // meaning and the element's OWN one is already rung 2; an ANCESTOR's is
      // the name of a SECTION, not of this field — taking it gave every input
      // inside `<div role="region" aria-label="Educational Details">` the
      // label "Educational Details". `aria-labelledby` holds ids, not text.
      if (/^aria-/i.test(attr.name)) continue;
      if (looksLikeHumanLabel(attr.value)) return attr.value.trim();
    }
  }
  return "";
}

/**
 * A label sitting in the same row as the field, with nothing tying them together
 * but layout.
 *
 * This is the case that produced a panel full of raw ids. The label is right
 * there, one line above the input, marked up as a `<label>` — with no `for`, no
 * wrapping, and no aria. Two containers are worth searching: one whose class
 * names the field (frameworks do this), and the ordinary "row" wrapper.
 */
function labelInSameRow(el: HTMLElement, key: string): Element | null {
  const containers: (Element | null)[] = [];
  if (key) containers.push(el.closest(`[class*="${CSS.escape(key)}"]`));
  containers.push(el.closest("[class*=row], [class*=Row], [class*=field], [class*=Field]"));
  containers.push(el.parentElement);
  for (const container of containers) {
    if (!container) continue;
    // Only claim a label from a container holding ONE control — a container
    // with several is a section, and its label belongs to none of them.
    if (container.querySelectorAll("input, select, textarea").length > 1) continue;
    const label = Array.from(container.querySelectorAll("label")).find(
      (l) => isVisible(l) && isUsableLabel(l.textContent),
    );
    if (label) return label;
  }
  return null;
}

/** The nearest `<label>` immediately before this field among its siblings. */
function precedingSiblingLabel(el: HTMLElement): Element | null {
  let node: Element | null = el.previousElementSibling;
  for (let i = 0; i < 3 && node; i += 1, node = node.previousElementSibling) {
    if (node.tagName === "LABEL" && isUsableLabel(node.textContent)) return node;
  }
  return null;
}

/**
 * What this field is called, tried in descending order of how sure the page is.
 *
 * Every rung is checked against `isUsableLabel` before it is believed, and a rung
 * that produces a widget state or a machine id counts as no answer at all. That
 * one rule is the whole fix: the chain used to take the first non-empty string
 * it found, which on a form with no `for` attributes meant the field's own id.
 */
/**
 * How this field is identified on the page.
 *
 * Usually its `id`. But a component framework can leave the visible `<input>`
 * with an EMPTY id and put the identity in `name` — the id belongs to the
 * wrapper that rendered it, and to a hidden template twin. Every convention
 * that names a label after its field then keys off the name instead, so the
 * ladder has to look there too. `for` is excluded on purpose: the HTML spec
 * says `for` matches an id and nothing else.
 */
function identityKey(el: HTMLElement): string {
  const id = el.getAttribute("id") ?? "";
  if (id !== "") return id;
  return el.getAttribute("name") ?? "";
}

/** How far up the tree the label hunt is allowed to walk. Raised from four
 *  after a real form put its row container one level beyond the old budget. */
const ANCESTOR_BUDGET = 6;

function labelInfo(el: HTMLElement): { text: string; required: boolean } {
  const id = el.getAttribute("id") ?? "";
  const key = identityKey(el);
  const doc = el.ownerDocument;
  const accept = (
    node: Element | null,
    text?: string,
  ): { text: string; required: boolean } | null => {
    const value = (text ?? node?.textContent ?? "").replace(/\s+/g, " ").trim();
    if (!isUsableLabel(value)) return null;
    return { text: value, required: classSaysRequired(node) };
  };

  // 1. What the HTML spec calls a label.
  if (id) {
    for (const lbl of Array.from(doc.querySelectorAll(`label[for="${CSS.escape(id)}"]`))) {
      const hit = accept(lbl);
      if (hit) return hit;
    }
  }
  const wrapping = el.closest("label");
  if (wrapping) {
    const hit = accept(wrapping, textWithoutControls(wrapping));
    if (hit) return hit;
  }

  // 2. What the page told assistive technology.
  const aria = accept(el, el.getAttribute("aria-label") ?? "");
  if (aria) return { text: aria.text, required: false };
  const labelledBy = el.getAttribute("aria-labelledby");
  if (labelledBy) {
    const text = labelledBy
      .split(/\s+/)
      .map((ref) => doc.getElementById(ref)?.textContent ?? "")
      .join(" ");
    const hit = accept(null, text);
    if (hit) return hit;
  }

  // 3. A naming convention between the label's id and this field's identity.
  if (key) {
    const hit = accept(labelByIdConvention(el, key));
    if (hit) return hit;
  }

  // 4. A component's own label property, on this element or an ancestor.
  const prop = labelFromAncestorProp(el, ANCESTOR_BUDGET);
  if (prop) return { text: prop, required: /\*/.test(prop) };

  // 5. The same row, then 6. a sibling just before.
  const row = accept(labelInSameRow(el, key));
  if (row) return row;
  const sibling = accept(precedingSiblingLabel(el));
  if (sibling) return sibling;

  // A placeholder is deliberately NOT tried here. It is a hint, not a name —
  // "Start typing..." over a field whose visible heading says "Location*" — and
  // `describe` reaches for the heading first, falling back to the placeholder
  // only when nothing else spoke at all.
  return { text: "", required: false };
}

/**
 * The words a person sees around a field the page never named.
 *
 * Collected only when every rung of the label chain came up empty, because a
 * label is better than its surroundings and there is no reason to carry both.
 * Walks up until there is enough text to be worth reading, then stops — the
 * whole form's text would tell the classifier nothing about THIS field.
 */
function contextTextFor(el: HTMLElement): string {
  let node: Element | null = el.parentElement;
  for (let depth = 0; depth < ANCESTOR_BUDGET && node; depth += 1, node = node.parentElement) {
    // A container with several controls describes all of them and none of them.
    if (node.querySelectorAll("input, select, textarea").length > 2) break;
    const text = textWithoutControls(node);
    if (text.length >= 3) return text.slice(0, 200);
  }
  return "";
}

/**
 * The named section a field sits in, when the page marked one out.
 *
 * A labelled region or a fieldset legend — the page saying "these fields belong
 * together and here is what they are about". Only history rows use it, and only
 * for fields whose own label is ambiguous about which history they serve.
 */
function sectionNameOf(el: HTMLElement): string {
  const region = el.closest<HTMLElement>(
    "[role=region][aria-label], fieldset, section[aria-label]",
  );
  if (!region) return "";
  const name =
    region.getAttribute("aria-label")?.trim() ??
    region.querySelector("legend")?.textContent?.replace(/\s+/g, " ").trim() ??
    "";
  return name;
}

/** Last resort: the placeholder. Worse than a heading, better than an id. */
function placeholderLabel(el: HTMLElement): string {
  const text = (el.getAttribute("placeholder") ?? "").replace(/\s+/g, " ").trim();
  return isUsableLabel(text) ? text : "";
}

function labelFor(el: HTMLElement): string {
  return labelInfo(el).text;
}

function isRequired(el: HTMLElement, label: string): boolean {
  // Native attribute and ARIA are authoritative; the "*" in a label is the
  // common ATS convention for custom widgets (react-select) that lack the attr.
  if ((el as HTMLInputElement).required || el.hasAttribute("required")) return true;
  if (el.getAttribute("aria-required") === "true") return true;
  return /\*/.test(label);
}

/** A Workday-style dropdown: a plain <button> that opens a listbox popup.
 *  Not a <select> and not a react-select combobox — its own scan/fill path. */
function isListboxButton(el: HTMLElement): boolean {
  return el instanceof HTMLButtonElement && el.getAttribute("aria-haspopup") === "listbox";
}

/** The button's rendered text is its current value; "Select One" (and the
 *  empty string) are Workday's unselected placeholders, not values. */
function listboxButtonValue(el: HTMLElement): string {
  const text = (el.textContent ?? "").replace(/\s+/g, " ").trim();
  return /^select one$/i.test(text) ? "" : text;
}

function describe(el: HTMLElement, used: Map<string, number>): FieldDescriptor {
  // Conventional label first; custom widgets with no label association (Ashby
  // comboboxes) fall back to the title element that precedes them — otherwise
  // the panel can only show the placeholder ("Start typing...").
  const li = labelInfo(el);
  const fallback = li.text ? null : precedingTitle(el, []);
  const label = li.text || fallback?.text || placeholderLabel(el);
  const titleRequired = li.required || fallback?.required || false;
  const name = el.getAttribute("name") || el.id || "";
  // A listbox button reports as "listbox", never its literal type="button":
  // it is semantically a select whose options exist only while the popup is
  // open, so the descriptor honestly carries no option list. Classification
  // still works from the label; options are matched live at fill time.
  // A control that opens a list reports as "listbox" whatever it is made of —
  // semantically a select whose options exist only while the popup is open, so
  // the descriptor honestly carries no option list and they are matched live at
  // fill time. Covers Workday's button and any ARIA combobox alike; without it
  // a `<div role="combobox">` would describe itself as type "div", which the
  // classifier and the panel would both read as free text.
  const isPopup = isListboxButton(el) || isAriaPopupControl(el);
  // A declared radiogroup is a choice group, and carries its option labels —
  // the answer bank and the AI option-picker both read those, so a group that
  // reported itself as a bare "div" would be unanswerable by either.
  const ariaGroup = el.getAttribute("role") === "radiogroup" ? ariaGroupMembers(el) : [];
  const type = isPopup
    ? "listbox"
    : ariaGroup.length > 0
      ? "radio-group"
      : (el.getAttribute("type") ?? el.tagName.toLowerCase()) || "text";
  const autocomplete = el.getAttribute("autocomplete") ?? "";
  const fieldId = stableFieldId(`${type}|${name}|${label}|${autocomplete}`, used);
  el.setAttribute("data-offeros-id", fieldId);
  return {
    fieldId,
    label,
    // `id` stands in when `name` is absent — real Greenhouse job-boards file
    // inputs carry id="resume"/id="cover_letter" with no name, and the id is
    // the only signal that tells the two "Attach" fields apart.
    name,
    autocomplete,
    type,
    placeholder: el.getAttribute("placeholder") ?? "",
    // Workday bakes the CURRENT value into the button's aria-label ("How Did
    // You Hear About Us? LinkedIn Required") — carrying it would let the
    // classifier read the value as a signal ("linkedin" → linkedin field).
    // The label association is authoritative for these; drop the aria-label.
    ariaLabel: type === "listbox" ? "" : (el.getAttribute("aria-label") ?? ""),
    required: isRequired(el, label) || titleRequired,
    ...(label === "" ? { contextText: contextTextFor(el) } : {}),
    ...(sectionNameOf(el) ? { sectionName: sectionNameOf(el) } : {}),
    ...(ariaGroup.length > 0 ? { options: ariaGroup.map(ariaOptionLabel).filter(Boolean) } : {}),
    currentValue:
      ariaGroup.length > 0
        ? (ariaGroup.find((m) => m.getAttribute("aria-checked") === "true")?.textContent ?? "")
            .replace(/\s+/g, " ")
            .trim()
        : currentValueOf(el, type),
    ...(ariaGroup.length > 0
      ? {
          currentValueIsPlaceholder: !ariaGroup.some(
            (m) => m.getAttribute("aria-checked") === "true",
          ),
        }
      : restingOnDefault(el) !== undefined
        ? { currentValueIsPlaceholder: restingOnDefault(el) }
        : {}),
  };
}

/**
 * Is this control resting on its own default, as the DOM itself says?
 *
 * The one place where "showing text" and "has been answered" can be told apart
 * on evidence rather than on wording. A `<select>` whose selected option
 * carries `value=""` is the universal convention for a prompt row, and a
 * disabled selected option can only be a prompt — nobody can choose it. Where
 * the DOM offers nothing (a div pretending to be a dropdown, which is most ATS
 * dropdowns), this returns false and the text patterns take over.
 */
/**
 * Whether this control is sitting on its own default — `undefined` when the
 * DOM cannot say either way.
 *
 * The three answers matter. `true` and `false` are both evidence, and both
 * outrank any guess made from the displayed text: a `<select>` whose selected
 * option is a real one has been answered even if that option reads "Unknown",
 * and a person who typed "N/A" into a box meant it. `undefined` is for the
 * controls the DOM genuinely cannot judge — a div pretending to be a dropdown,
 * or a composite phone widget showing its dial code — and only those fall
 * through to reading the words.
 */
function restingOnDefault(el: HTMLElement): boolean | undefined {
  if (el instanceof HTMLSelectElement) {
    if (el.selectedIndex < 0) return true;
    const option = el.options[el.selectedIndex];
    if (!option) return true;
    // `value=""` is the prompt-row convention; `disabled` cannot be a choice.
    if ((option.getAttribute("value") ?? "") === "") return true;
    if (option.disabled) return true;
    return false;
  }
  if (el instanceof HTMLInputElement && (el.type === "checkbox" || el.type === "radio")) {
    return !el.checked;
  }
  // A typed value is content, not furniture: the placeholder ATTRIBUTE never
  // reaches `value`. `tel` is excluded because composite phone widgets report
  // their country picker as the value, which is furniture.
  if (el instanceof HTMLTextAreaElement) return el.value.trim() === "" ? undefined : false;
  if (el instanceof HTMLInputElement && TYPED_TEXT_TYPES.has(el.type)) {
    return el.value.trim() === "" ? undefined : false;
  }
  return undefined;
}

/** Input types whose `value` is something a person typed, not a widget's label. */
const TYPED_TEXT_TYPES = new Set(["text", "email", "url", "search", "number"]);

/** The control's live value at scan time. File inputs report the chosen file
 *  name (value is a fakepath); everything else the raw value property. */
function currentValueOf(el: HTMLElement, type: string): string {
  if (type === "file") {
    const f = (el as HTMLInputElement).files?.[0];
    return f ? f.name : "";
  }
  if (type === "listbox") {
    return isListboxButton(el) ? listboxButtonValue(el) : ariaControlValue(el);
  }
  const v = (el as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement).value;
  return typeof v === "string" ? v : "";
}

/**
 * Parts of a widget are not questions.
 *
 * A composite control — a country-code picker, a typeahead, any dropdown with a
 * filter — is built out of inputs, and scanning them as fields turns one
 * question into three: the control itself, its search box, and whatever
 * transient row the popup happened to be showing. On a real form this produced
 * "Search country with dial code" listed as something the applicant had been
 * asked.
 *
 * Two shapes are recognised, both by role rather than by any site's markup: an
 * input living inside a listbox/option/menu container, and a search box sitting
 * next to one.
 */
function isInsideComposite(el: HTMLElement): boolean {
  return el.closest('[role="listbox"], [role="option"], [role="menu"], [role="menuitem"]') !== null;
}

/** A filter box for the popup beside it, rather than a field of its own. */
function isWidgetSearchBox(el: HTMLElement): boolean {
  const hint = `${el.getAttribute("placeholder") ?? ""} ${el.getAttribute("aria-label") ?? ""}`;
  if (!/\bsearch\b|\bfilter\b|type to (search|filter)/i.test(hint)) return false;
  // Only when it actually belongs to a popup: a page's own "Search jobs" box is
  // not a form field either, but it is not this function's business.
  const scope = el.closest(
    '[class*="dropdown"], [class*="select"], [class*="combo"], [role="combobox"]',
  );
  if (scope) return true;
  const doc = el.ownerDocument;
  const near = el.parentElement?.parentElement ?? doc.body;
  return near?.querySelector('[role="listbox"], [role="option"]') !== null;
}

function isScannable(el: HTMLElement): boolean {
  if (el.getAttribute("name") === "g-recaptcha-response") return false;
  if (el.closest('[aria-hidden="true"]')) return false;
  // A <template>'s contents are inert markup waiting to be cloned, and a
  // component framework's own template twin is the same thing by another name.
  // Both carry a full copy of every field — ids, names and all — so scanning
  // them lists every question twice and lets the copy nobody can see win the
  // label lookup.
  if (el.closest('template, [is="component"]')) return false;
  const style = el.ownerDocument.defaultView?.getComputedStyle(el);
  const hidden = style ? style.display === "none" || style.visibility === "hidden" : false;
  // A file input is the one control routinely hidden ON PURPOSE: a custom
  // uploader hides the real `<input type="file">` and renders its own button
  // over it, because the native control cannot be styled. Rejecting it for
  // being invisible means the résumé upload on every such form is a field
  // OfferOS cannot see — which is exactly what happened. Everything else
  // hidden is still skipped.
  if (hidden && !isFileInput(el)) return false;
  // A widget's own machinery, not a question the applicant was asked.
  if (isInsideComposite(el) || isWidgetSearchBox(el)) return false;
  return true;
}

function isFileInput(el: Element): el is HTMLInputElement {
  return el instanceof HTMLInputElement && el.type === "file";
}

/**
 * The real file input behind a custom uploader.
 *
 * Custom uploaders wrap the native control in a component and hide it, so the
 * element a descriptor points at is often the wrapper rather than the input.
 * Search inside it first, then widen a few ancestors — stopping as soon as a
 * scope holds more than one, because two uploads in one region is a choice
 * this cannot make.
 */
export function findFileInputNear(el: HTMLElement): HTMLInputElement | null {
  if (isFileInput(el)) return el;
  // An ordinary control is a field in its own right, not a wrapper around
  // something else. Widening from a text box would let "attach to the name
  // field" quietly attach to whatever upload happens to be nearby.
  if (
    el instanceof HTMLInputElement ||
    el instanceof HTMLSelectElement ||
    el instanceof HTMLTextAreaElement
  ) {
    return null;
  }
  const within = deepQueryAll(el, 'input[type="file"]').filter(isFileInput);
  if (within.length === 1) return within[0]!;
  let node: HTMLElement | null = el.parentElement;
  for (let depth = 0; depth < ANCESTOR_BUDGET && node; depth += 1, node = node.parentElement) {
    const found = deepQueryAll(node, 'input[type="file"]').filter(isFileInput);
    if (found.length === 1) return found[0]!;
    if (found.length > 1) return null;
  }
  return null;
}

/** The question/title text that precedes a control: walk up from it and take
 *  the first content BEFORE it whose text isn't one of `excludeTexts`
 *  (option labels for groups; empty for single controls). ATSes render
 *  "question title, then control" without label association — Ashby's choice
 *  groups AND its custom comboboxes ("Location*" above an unlabeled
 *  "Start typing..." input) both resolve through this. */
function precedingTitle(
  first: HTMLElement,
  excludeTexts: string[],
): { text: string; required: boolean } | null {
  let node: HTMLElement | null = first.closest("label")?.parentElement ?? first.parentElement;
  for (let depth = 0; depth < ANCESTOR_BUDGET && node; depth += 1, node = node.parentElement) {
    for (const child of Array.from(node.children)) {
      if (child.contains(first)) break; // only content that precedes the options
      const text = (child.textContent ?? "").replace(/\s+/g, " ").trim();
      // Same bar as every other rung: a widget state or a machine id found by
      // walking the tree is not a better answer than none.
      if (isUsableLabel(text) && !excludeTexts.includes(text)) {
        return { text, required: classSaysRequired(child) };
      }
    }
  }
  return null;
}

/** Grouping key for one choice control: radios group by their shared `name`;
 *  checkbox option rows (Ashby) share an id prefix `…-labeled-checkbox-N`.
 *  Null = not part of a group (a lone consent checkbox stays a single field). */
function choiceGroupKey(el: HTMLElement): string | null {
  const type = el.getAttribute("type");
  if (type === "radio") {
    const name = el.getAttribute("name");
    return name ? `radio:${name}` : null;
  }
  if (type === "checkbox") {
    const m = /^(.+)-labeled-checkbox-\d+$/.exec(el.id);
    return m ? `checkbox:${m[1]}` : null;
  }
  return null;
}

function describeGroup(
  members: HTMLElement[],
  key: string,
  used: Map<string, number>,
): FieldDescriptor {
  const first = members[0]!;
  const options = members.map((m) => labelFor(m)).filter((t) => t !== "");
  const title = precedingTitle(first, options);
  const question = title?.text ?? "";
  const fieldId = stableFieldId(`group|${key}|${question}`, used);
  first.setAttribute("data-offeros-id", fieldId);
  return {
    fieldId,
    label: question,
    name: key,
    autocomplete: "",
    type: key.startsWith("radio:") ? "radio-group" : "checkbox-group",
    placeholder: "",
    ariaLabel: "",
    required:
      members.some((m) => (m as HTMLInputElement).required) ||
      /\*/.test(question) ||
      (title?.required ?? false),
    options,
    currentValue: members
      .filter((m) => (m as HTMLInputElement).checked)
      .map((m) => labelFor(m))
      .filter((t) => t !== "")
      .join(", "),
  };
}

/** A control with no signal at all (no label, name, aria, or placeholder) is
 *  unactionable and unclassifiable — pure noise in the panel (e.g. Ashby's own
 *  "autofill from resume" file input). */
function hasAnySignal(el: HTMLElement): boolean {
  return Boolean(
    labelFor(el) ||
    el.getAttribute("name") ||
    el.id ||
    el.getAttribute("aria-label") ||
    el.getAttribute("placeholder"),
  );
}

/**
 * Build one descriptor from what the ATS itself said about a question.
 *
 * Everything here is read, not inferred: the question text is the platform's
 * own, the option list is the platform's own, and requiredness came from the
 * field definition rather than from spotting an asterisk in a label.
 */
function describeFromMeta(
  meta: FieldMeta,
  members: HTMLElement[],
  used: Map<string, number>,
): FieldDescriptor {
  const first = members[0]!;
  const single = members.length === 1;
  const choice = meta.control === "single-select" || meta.control === "multi-select";
  // Options the platform enumerated beat labels scraped off the members; fall
  // back to the members' own text only when it enumerated nothing.
  const options =
    meta.options ?? (single ? undefined : members.map((m) => labelFor(m)).filter((t) => t !== ""));
  const fieldId = stableFieldId(`meta|${meta.groupId}`, used);
  first.setAttribute("data-offeros-id", fieldId);
  const type =
    !single || (choice && options?.length)
      ? meta.control === "multi-select"
        ? "checkbox-group"
        : "radio-group"
      : (first.getAttribute("type") ?? first.tagName.toLowerCase());
  return {
    fieldId,
    label: meta.question,
    name: meta.groupId,
    autocomplete: first.getAttribute("autocomplete") ?? "",
    type,
    placeholder: first.getAttribute("placeholder") ?? "",
    ariaLabel: first.getAttribute("aria-label") ?? "",
    required: meta.required,
    ...(options?.length ? { options } : {}),
    currentValue: single
      ? currentValueOf(first, type)
      : members
          .filter((m) => (m as HTMLInputElement).checked)
          .map((m) => labelFor(m))
          .filter((t) => t !== "")
          .join(", "),
  };
}

/**
 * One field per id, and the one a person can see.
 *
 * Duplicate ids are invalid HTML and completely routine: a form renders its
 * fields once for real and once as a hidden template, both carrying the same
 * id. Scanning both listed every question twice, and the copy that won the
 * label lookup was whichever came first in the document — which on such a page
 * is the template, the one with no label attached to it.
 */
function preferVisibleTwins(els: HTMLElement[]): HTMLElement[] {
  const byId = new Map<string, HTMLElement>();
  const out: HTMLElement[] = [];
  for (const el of els) {
    const id = el.getAttribute("id");
    if (!id) {
      out.push(el);
      continue;
    }
    const seen = byId.get(id);
    if (!seen) {
      byId.set(id, el);
      out.push(el);
      continue;
    }
    // Already have one under this id: keep whichever is visible.
    if (!isVisible(seen) && isVisible(el)) {
      out[out.indexOf(seen)] = el;
      byId.set(id, el);
    }
  }
  return out;
}

export function scanFields(
  root: ParentNode,
  recipe: AtsRecipe,
  /** What the ATS says about its own fields, when the page exposes it. Absent
   *  or empty leaves every heuristic below exactly as it was. */
  metaByEl?: Map<Element, FieldMeta>,
): { descriptor: FieldDescriptor; el: HTMLElement }[] {
  const form = root.querySelector(recipe.formSelector) ?? root;
  // Workday renders inputs inside web-component shadow roots; pierce them when
  // the recipe opts in.
  const raw = recipe.pierceShadow
    ? deepQueryAll(form, recipe.fieldSelector).filter(
        (el): el is HTMLElement => el instanceof HTMLElement,
      )
    : Array.from(form.querySelectorAll<HTMLElement>(recipe.fieldSelector));
  const els = preferVisibleTwins(raw.filter(isScannable).filter(hasAnySignal));

  // Collapse choice groups (radio sets, Ashby checkbox option rows) into ONE
  // logical field each, keyed by the group's question — option rows were
  // previously scanned as N bogus fields and even text-classified ("New York
  // City Office" → city).
  const out: { descriptor: FieldDescriptor; el: HTMLElement }[] = [];
  const usedIds = new Map<string, number>();

  // Fields the ATS described itself are settled before any guessing starts, and
  // are removed from what follows. This is the whole point: grouping by the
  // platform's own field id cannot mistake eight race checkboxes for eight
  // questions the way DOM proximity did.
  const describedByMeta = new Set<HTMLElement>();
  if (metaByEl?.size) {
    for (const { meta, members } of groupByMeta(metaByEl, els)) {
      out.push({ descriptor: describeFromMeta(meta, members, usedIds), el: members[0]! });
      for (const m of members) describedByMeta.add(m);
    }
  }

  const grouped = new Map<string, HTMLElement[]>();
  for (const el of els) {
    if (describedByMeta.has(el)) continue;
    const key = choiceGroupKey(el);
    if (key) {
      const list = grouped.get(key) ?? [];
      list.push(el);
      grouped.set(key, list);
    }
  }
  const seenGroups = new Set<string>();
  for (const el of els) {
    if (describedByMeta.has(el)) continue;
    const key = choiceGroupKey(el);
    if (key && (grouped.get(key)?.length ?? 0) >= 2) {
      if (!seenGroups.has(key)) {
        seenGroups.add(key);
        const members = grouped.get(key)!;
        out.push({ descriptor: describeGroup(members, key, usedIds), el: members[0]! });
      }
      continue; // members beyond the first are folded into the group
    }
    out.push({ descriptor: describe(el, usedIds), el });
  }

  // Ashby "Yes/No" widgets: a display:none checkbox behind two visible
  // buttons. The hidden input fails isScannable, so without this pass the
  // question is entirely invisible to the panel (observed on real postings:
  // work-authorization / commute / policy-consent questions all use it).
  for (const container of Array.from(form.querySelectorAll<HTMLElement>('div[class*="_yesno"]'))) {
    const hiddenInput = container.querySelector<HTMLInputElement>('input[type="checkbox"]');
    const buttons = Array.from(container.querySelectorAll("button"));
    const options = buttons.map((b) => (b.textContent ?? "").trim()).filter((t) => t !== "");
    if (!hiddenInput || options.length < 2) continue;
    const title = precedingTitle(container, options);
    const question = title?.text ?? "";
    const name = hiddenInput.getAttribute("name") || hiddenInput.id || "";
    const fieldId = stableFieldId(`group|yesno:${name}|${question}`, usedIds);
    container.setAttribute("data-offeros-id", fieldId);
    out.push({
      descriptor: {
        fieldId,
        label: question,
        name: `yesno:${name}`,
        autocomplete: "",
        // Semantically a single-choice group — reuses the whole choice-group
        // pipeline (classification short-circuit, answer-bank/AI option fill).
        type: "radio-group",
        placeholder: "",
        ariaLabel: "",
        required: /\*/.test(question) || (title?.required ?? false),
        options,
        currentValue:
          buttons.find((b) => /(^|\s)_active_/.test(b.className))?.textContent?.trim() ?? "",
      },
      el: container,
    });
  }

  // The yes/no pass appends out of document order — restore it so the panel's
  // field list reads top-to-bottom like the page. Ids are already assigned, so
  // sorting cannot destabilize them.
  out.sort((a, b) =>
    a.el.compareDocumentPosition(b.el) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1,
  );
  return out;
}

/** All inputs belonging to the same choice group as `first` (see
 *  choiceGroupKey): radios by shared name, Ashby checkbox rows by id prefix. */
function groupMembers(doc: Document, first: HTMLInputElement): HTMLInputElement[] {
  if (first.type === "radio" && first.name) {
    return Array.from(
      doc.querySelectorAll<HTMLInputElement>(
        `input[type="radio"][name="${CSS.escape(first.name)}"]`,
      ),
    );
  }
  const m = /^(.+)-labeled-checkbox-\d+$/.exec(first.id);
  if (m) {
    const prefix = `${m[1]}-labeled-checkbox-`;
    return Array.from(doc.querySelectorAll<HTMLInputElement>('input[type="checkbox"]')).filter(
      (el) => el.id.startsWith(prefix),
    );
  }
  return [first];
}

/** Answer a choice group by clicking the option whose visible label matches
 *  `value` (tolerant matching via matchOption). Verified via .checked — a
 *  real click that React observes natively. Null when no option matches
 *  or the click didn't take. */
function fillChoiceGroup(
  doc: Document,
  first: HTMLInputElement,
  value: string,
): HTMLInputElement | null {
  const members = groupMembers(doc, first);
  const labels = members.map((m) => labelFor(m));
  const target = matchOption(
    labels.map((l) => ({ label: l, value: l })),
    value,
  );
  if (!target) return null;
  const el = members[labels.indexOf(String(target.label ?? ""))];
  if (!el) return null;
  el.click();
  if (!el.checked) {
    el.checked = true;
    el.dispatchEvent(new Event("change", { bubbles: true }));
  }
  return el.checked ? el : null;
}

/** An Ashby yes/no widget container (see the scan pass above). */
function isYesNoWidget(el: HTMLElement): boolean {
  return el instanceof HTMLDivElement && /(?:^|\s)_yesno/.test(el.className);
}

/** Answer a yes/no widget by clicking the matching visible button. React
 *  applies the selection asynchronously, so verification polls briefly for
 *  the button's active class before declaring the click landed. */
async function fillYesNoWidget(container: HTMLElement, value: string): Promise<boolean> {
  const buttons = Array.from(container.querySelectorAll("button"));
  const labels = buttons.map((b) => (b.textContent ?? "").trim());
  const target = matchOption(
    labels.map((l) => ({ label: l, value: l })),
    value,
  );
  if (!target) return false;
  const btn = buttons[labels.indexOf(String(target.label ?? ""))];
  if (!btn) return false;
  if (/(^|\s)_active_/.test(btn.className)) return true; // already selected
  btn.click();
  const win = container.ownerDocument.defaultView;
  for (let i = 0; i < 10; i += 1) {
    if (/(^|\s)_active_/.test(btn.className)) return true;
    await new Promise((r) => (win ?? window).setTimeout(r, 60));
  }
  return /(^|\s)_active_/.test(btn.className);
}

/**
 * Answer a Workday listbox-button dropdown: click the button, wait for the
 * popup listbox (a portal appended near <body> — detected as a [role=listbox]
 * that was NOT there before the click, because the phone-code multiselect
 * keeps a permanent pill listbox on the page), match the wanted value against
 * the live [role=option] rows, click the match, and verify the button's
 * rendered text changed to the chosen option. Plain DOM widget — an
 * isolated-world click sequence suffices; no MAIN-world driver needed
 * (verified live on a wd1.myworkdayjobs.com tenant).
 */
async function fillListboxButton(el: HTMLElement, value: string): Promise<boolean> {
  const doc = el.ownerDocument;
  const win = doc.defaultView;
  const sleep = (ms: number) => new Promise((r) => (win ?? window).setTimeout(r, ms));
  const listboxes = () => Array.from(doc.querySelectorAll<HTMLElement>('[role="listbox"]'));
  const current = listboxButtonValue(el);
  if (current !== "" && matchOption([{ label: current, value: current }], value) !== null) {
    return true; // already showing the wanted option — never reopen a settled field
  }
  const before = new Set(listboxes());
  el.click();
  let popup: HTMLElement | undefined;
  for (let i = 0; i < 20 && !popup; i += 1) {
    await sleep(100);
    popup = listboxes().find((lb) => !before.has(lb));
  }
  if (!popup) return false;
  const closePopup = () => {
    // Escape is unreliable on this widget (observed live); the button toggles.
    if (popup?.isConnected) el.click();
  };
  const opts = Array.from(popup.querySelectorAll<HTMLElement>('[role="option"]'));
  const target = matchOption(
    opts.map((o, idx) => ({ label: (o.textContent ?? "").trim(), value: idx })),
    value,
  );
  const hit = target && typeof target.value === "number" ? opts[target.value] : undefined;
  if (!target || !hit) {
    closePopup();
    return false;
  }
  const want = String(target.label ?? "");
  // Real mouse sequence, same as the MAIN-world react-select fallback uses.
  hit.dispatchEvent(new MouseEvent("mousedown", { bubbles: true, cancelable: true, button: 0 }));
  hit.dispatchEvent(new MouseEvent("mouseup", { bubbles: true, cancelable: true, button: 0 }));
  hit.click();
  for (let i = 0; i < 10; i += 1) {
    const now = listboxButtonValue(el);
    // The widget may re-render the label slightly (ellipsis, spacing) — accept
    // any rendered text the shared matcher maps to the chosen option.
    if (now !== "" && matchOption([{ label: now, value: now }], want) !== null) return true;
    await sleep(100);
  }
  closePopup();
  return false;
}

type Fillable = HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement;

export function setControlledValue(el: Fillable, value: string): void {
  const proto =
    el instanceof HTMLTextAreaElement
      ? HTMLTextAreaElement.prototype
      : el instanceof HTMLSelectElement
        ? HTMLSelectElement.prototype
        : HTMLInputElement.prototype;
  const setter = Object.getOwnPropertyDescriptor(proto, "value")?.set;
  if (setter) setter.call(el, value);
  else el.value = value;
  el.dispatchEvent(new Event("input", { bubbles: true }));
  el.dispatchEvent(new Event("change", { bubbles: true }));
}

/**
 * Attach a file to a file <input> by assigning a synthetic DataTransfer's
 * FileList, then dispatching input+change so any React/JS listener on the
 * field observes it. Verifies by re-reading `input.files` afterward — a
 * site that ignores the programmatic assignment (or clears it) must not be
 * reported as filled; the caller falls back to the manual-attach reason on
 * a false return.
 */
export function attachFile(input: HTMLInputElement, file: File): boolean {
  const dt = new DataTransfer();
  dt.items.add(file);
  input.files = dt.files;
  input.dispatchEvent(new Event("input", { bubbles: true }));
  input.dispatchEvent(new Event("change", { bubbles: true }));
  const attached = input.files;
  return attached !== null && attached.length === 1 && attached[0]?.name === file.name;
}

export function highlight(el: HTMLElement): void {
  el.classList.add("offeros-filled");
  el.ownerDocument.defaultView?.setTimeout(() => el.classList.remove("offeros-filled"), 800);
}

export function resolveFieldEl(doc: Document, fieldId: string): HTMLElement | null {
  return doc.querySelector<HTMLElement>(`[data-offeros-id="${CSS.escape(fieldId)}"]`);
}

function isComboboxInput(el: HTMLElement): boolean {
  return (
    el instanceof HTMLInputElement &&
    (el.getAttribute("role") === "combobox" || el.getAttribute("aria-autocomplete") === "list")
  );
}

function fillComboboxViaDriver(
  el: HTMLElement,
  fieldId: string,
  value: string,
  timeoutMs: number,
): Promise<boolean> {
  const win = el.ownerDocument.defaultView;
  if (!win) return Promise.resolve(false);
  return new Promise((resolve) => {
    const finish = (ok: boolean) => {
      win.clearTimeout(timer);
      win.removeEventListener("message", onMessage);
      resolve(ok);
    };
    const timer = win.setTimeout(() => finish(false), timeoutMs);
    function onMessage(ev: MessageEvent) {
      const d: unknown = ev.data;
      if (!isComboboxResultMsg(d) || d.fieldId !== fieldId) return;
      finish(d.ok);
    }
    win.addEventListener("message", onMessage);
    win.postMessage({ kind: COMBOBOX_FILL, fieldId, value }, "*");
  });
}

function fillSkillsViaDriver(
  doc: Document,
  fieldId: string,
  values: string[],
  timeoutMs: number,
): Promise<number> {
  const win = doc.defaultView;
  if (!win) return Promise.resolve(0);
  return new Promise((resolve) => {
    const finish = (filled: number) => {
      win.clearTimeout(timer);
      win.removeEventListener("message", onMessage);
      resolve(filled);
    };
    const timer = win.setTimeout(() => finish(0), timeoutMs);
    function onMessage(ev: MessageEvent) {
      const d: unknown = ev.data;
      if (!isSkillsResultMsg(d) || d.fieldId !== fieldId) return;
      finish(d.filled);
    }
    win.addEventListener("message", onMessage);
    win.postMessage({ kind: SKILLS_FILL, fieldId, values }, "*");
  });
}

export type FillValue = { fieldId: string; value: string } | { fieldId: string; values: string[] };

/**
 * The field was there when the page was read and is not there now — a
 * re-render between the scan and the write, which is ordinary on a form that
 * rebuilds sections as you fill them.
 */
export const FIELD_GONE_REASON =
  "This field is no longer on the page — it may have been rebuilt while filling. Re-scan and try again.";

/** A control none of the drivers above can operate. */
export const UNSUPPORTED_CONTROL_REASON = "OfferOS can't operate this control — set it yourself.";

/**
 * What one write did. The object form carries a reason the page explains — a
 * field that took the value and then dropped it says something a bare
 * `"failed"` cannot, and form memory reads these. A `"filled"` can carry one
 * too, for a write that landed by a route the user should know about (a
 * dropdown that never opened and was typed into instead).
 */
export type FillOutcome =
  | "filled"
  | "failed"
  | {
      outcome: "filled" | "failed";
      reason?: string;
      /** Actual control value immediately before/after this write. These are
       * added at the engine boundary, where a fresh scan can read custom
       * widgets as well as native inputs. */
      before?: string;
      after?: string;
    };

/**
 * Did the page keep what we typed?
 *
 * An exact match is the easy case. The rest is a text field's ordinary right to
 * reformat: a phone mask turning 5551234567 into (555) 123-4567, a date field
 * re-punctuating, whitespace trimmed. Those are the same answer, so compare on
 * the characters that carry meaning. What is left over — an empty field, or one
 * holding something else entirely — is a write the form did not accept.
 */
export function textWriteLanded(want: string, got: string): boolean {
  if (got === want) return true;
  const squash = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");
  return squash(got) === squash(want);
}

/**
 * Fill the given values into the live page, returning the count of verified
 * writes plus a per-field outcome map for task mode's field reports. A field
 * appears in `outcomes` only when it was actually attempted: `"filled"` on a
 * verified write, `"failed"` when a combobox/skills driver declined it or the
 * page did not keep a text write. Fields skipped entirely (element gone, file
 * input, empty skills list) are absent — the caller reports them from the plan
 * status instead.
 */
export async function applyFillDetailed(
  doc: Document,
  values: FillValue[],
  opts?: { comboTimeoutMs?: number; skillsTimeoutMs?: number },
): Promise<{ filled: number; outcomes: Map<string, FillOutcome> }> {
  const timeoutMs = opts?.comboTimeoutMs ?? 2500;
  const skillsTimeoutMs = opts?.skillsTimeoutMs ?? 15000;
  const outcomes = new Map<string, FillOutcome>();
  let filled = 0;
  for (const item of values) {
    // Skills: a multi-value tag field. Route the whole list to the driver loop.
    if ("values" in item) {
      if (!resolveFieldEl(doc, item.fieldId)) {
        outcomes.set(item.fieldId, { outcome: "failed", reason: FIELD_GONE_REASON });
      } else if (item.values.length > 0) {
        const tagged = await fillSkillsViaDriver(doc, item.fieldId, item.values, skillsTimeoutMs);
        if (tagged > 0) {
          filled++;
          outcomes.set(item.fieldId, "filled");
        } else {
          outcomes.set(item.fieldId, "failed");
        }
      }
      continue;
    }
    const { fieldId, value } = item;
    const el = resolveFieldEl(doc, fieldId);
    // Workday listbox-button dropdowns: click-through driver with live option
    // matching. A miss reports "failed" — the panel shows a needs-user row.
    if (el && isListboxButton(el)) {
      if (await fillListboxButton(el, value)) {
        highlight(el);
        filled++;
        outcomes.set(fieldId, "filled");
      } else {
        outcomes.set(fieldId, "failed");
      }
      continue;
    }
    if (el && isYesNoWidget(el)) {
      if (await fillYesNoWidget(el, value)) {
        highlight(el);
        filled++;
        outcomes.set(fieldId, "filled");
      } else {
        outcomes.set(fieldId, "failed");
      }
      continue;
    }
    // The generic layer, AFTER every site-specific driver above. Those are
    // faster and more precise where they apply; this only sees a control none
    // of them recognised. It goes by what the page declared about itself in
    // ARIA — the one description a custom widget usually supplies whatever it
    // was built out of — and, like every path here, reports only what the page
    // confirms.
    if (el && isAriaPopupControl(el)) {
      const res = await fillAriaPopup(el, value);
      if (res.ok) {
        highlight(el);
        filled++;
        // A caveat on a success still reaches the report, so "filled" never
        // quietly means "filled by a route you would want to check".
        outcomes.set(fieldId, res.reason ? { outcome: "filled", reason: res.reason } : "filled");
      } else {
        outcomes.set(fieldId, { outcome: "failed", reason: res.reason ?? "" });
      }
      continue;
    }
    if (el && isAriaChoice(el)) {
      const res = await fillAriaChoice(el, value);
      if (res.ok) {
        highlight(el);
        filled++;
        outcomes.set(fieldId, "filled");
      } else {
        outcomes.set(fieldId, { outcome: "failed", reason: res.reason ?? "" });
      }
      continue;
    }
    // A file input is filled by the attach path, which reports it from the
    // plan. Absence from `outcomes` is correct here — and ONLY here.
    if (el instanceof HTMLInputElement && el.type === "file") continue;

    if (!(
      el instanceof HTMLInputElement ||
      el instanceof HTMLTextAreaElement ||
      el instanceof HTMLSelectElement
    )) {
      // Everything that reaches this line was asked for and cannot be
      // delivered, and it used to leave without saying so. The caller writes
      // "skipped" for any field with no outcome, which is its word for a
      // control we deliberately left alone — so a field we had the answer for
      // came out indistinguishable from one we were right to ignore, and every
      // consumer downstream (the hand-back list, the diagnosis, the required
      // count) passed over it. A real application went out with three Equal
      // Employment dropdowns and a phone number empty this way.
      outcomes.set(fieldId, {
        outcome: "failed",
        reason: el === null ? FIELD_GONE_REASON : UNSUPPORTED_CONTROL_REASON,
      });
      continue;
    }
    if (el instanceof HTMLInputElement && (el.type === "radio" || el.type === "checkbox")) {
      const picked = fillChoiceGroup(doc, el, value);
      if (picked) {
        highlight(picked);
        filled++;
        outcomes.set(fieldId, "filled");
      } else {
        outcomes.set(fieldId, "failed");
      }
      continue;
    }
    if (isComboboxInput(el)) {
      // No retry rung here on purpose: when the driver can't drive a
      // react-select, typing into its visible input leaves the underlying
      // selection unset — the field submits empty while the input LOOKS
      // filled. Reporting "failed" keeps the panel honest; the user gets a
      // needs-user row that jumps straight to the control.
      if (await fillComboboxViaDriver(el, fieldId, value, timeoutMs)) {
        highlight(el);
        filled++;
        outcomes.set(fieldId, "filled");
      } else {
        outcomes.set(fieldId, "failed");
      }
      continue;
    }
    // A native <select> only accepts one of its own option values: assigning
    // anything else (a label like "United States" against value="US") is
    // silently reset to "" by the browser, so a raw write would report a field
    // as filled that the form will reject. Resolve the option first — with the
    // shared geo/synonym matcher — and verify the selection landed.
    if (el instanceof HTMLSelectElement) {
      const option = matchOptionValue([...el.options], value);
      const optionValue = option ? String((option as HTMLOptionElement).value ?? "") : "";
      if (option && optionValue !== "") {
        setControlledValue(el, optionValue);
      }
      if (el.value !== "" && (!option || el.value === optionValue)) {
        highlight(el);
        filled++;
        outcomes.set(fieldId, "filled");
      } else {
        outcomes.set(fieldId, "failed");
      }
      continue;
    }
    // Every other path above verifies its write before claiming it. This one
    // used to just report "filled" — so a React field that rejects a
    // programmatic value and re-renders its own empty state was reported as
    // answered, and the form arrived at submit with a blank required field that
    // nothing downstream knew to flag.
    setControlledValue(el, value);
    const got = el.value;
    if (!textWriteLanded(value, got)) {
      outcomes.set(fieldId, {
        outcome: "failed",
        reason:
          got.trim() === ""
            ? "The page cleared this field right after it was filled — type it in yourself."
            : `The page changed this to "${got}" after it was filled — check it.`,
      });
      continue;
    }
    highlight(el);
    filled++;
    outcomes.set(fieldId, "filled");
  }
  return { filled, outcomes };
}
